export const DEFAULT_MATCH_AVATAR = '/assets/users-cards-icons/user2.jpg';
export const MAX_CHAT_NOTIFICATIONS = 20;

export const CHAT_NOTIFICATION_STORE = {
  items: [],
  unreadCount: 0,
  nextId: 1,
};

export const WEBRTC_ICE_SERVERS = [{ urls: 'stun:stun.l.google.com:19302' }];

export const WEBRTC_MEDIA_CONSTRAINTS = {
  video: true,
  audio: true,
};

export const CHAT_UPLOAD_MAX_BYTES = 10 * 1024 * 1024;

export const CHAT_IMAGE_EXTENSIONS = new Set([
  'jpg',
  'jpeg',
  'png',
  'gif',
  'webp',
]);

export const CHAT_AUDIO_EXTENSIONS = new Set([
  'mp3',
  'ogg',
  'wav',
  'webm',
]);

export const CHAT_IMAGE_MIME_TYPES = new Set([
  'image/jpeg',
  'image/png',
  'image/gif',
  'image/webp',
]);

export const CHAT_AUDIO_MIME_TYPES = new Set([
  'audio/mpeg',
  'audio/mp3',
  'audio/ogg',
  'audio/wav',
  'audio/x-wav',
  'audio/webm',
]);

export const CHAT_RECORDING_MAX_MS = 120000;

export const CHAT_RECORDING_MIME_CANDIDATES = [
  'audio/webm;codecs=opus',
  'audio/webm',
  'audio/ogg;codecs=opus',
  'audio/ogg',
];

export const FEED_CATEGORY_RULES = [
  {
    key: 'programacion',
    title: 'Programacion',
    subtitle: 'Perfiles de desarrollo y tecnologia',
    keywords: [
      'programacion',
      'programar',
      'desarrollo',
      'developer',
      'desarrollador',
      'desarrolladora',
      'frontend',
      'backend',
      'fullstack',
      'full stack',
      'javascript',
      'js',
      'typescript',
      'ts',
      'python',
      'java',
      'golang',
      'go',
      'node',
      'nodejs',
      'react',
      'vue',
      'angular',
      'api',
      'rest',
      'graphql',
      'sql',
      'mongodb',
      'postgres',
      'postgresql',
      'mysql',
      'firebase',
      'docker',
      'kubernetes',
      'devops',
      'ci/cd',
      'c#',
      'c++',
      'dotnet',
      '.net',
      'php',
      'ruby',
      'swift',
      'kotlin',
      'flask',
      'django',
      'laravel',
      'spring',
      'algoritmos',
      'estructura de datos',
      'software',
    ],
  },
  {
    key: 'idiomas',
    title: 'Idiomas',
    subtitle: 'Perfiles para intercambio de idiomas',
    keywords: [
      'idioma',
      'idiomas',
      'language',
      'languages',
      'ingles',
      'english',
      'frances',
      'french',
      'portugues',
      'portuguese',
      'espanol',
      'spanish',
      'aleman',
      'german',
      'italiano',
      'italian',
      'chino',
      'chinese',
      'mandarin',
      'japones',
      'japanese',
      'ruso',
      'russian',
      'coreano',
      'korean',
      'traduccion',
      'translation',
      'pronunciacion',
      'gramatica',
      'conversation',
      'conversacion',
    ],
  },
  {
    key: 'diseno',
    title: 'Diseno',
    subtitle: 'Perfiles creativos y visuales',
    keywords: [
      'diseno',
      'design',
      'graphic design',
      'diseno grafico',
      'ux',
      'ui',
      'ux/ui',
      'figma',
      'photoshop',
      'illustrator',
      'after effects',
      'premiere',
      'canva',
      'branding',
      'creatividad',
      'animacion',
      '3d',
      'motion',
      'prototipo',
      'wireframe',
      'product design',
    ],
  },
  {
    key: 'negocios',
    title: 'Negocios y Productividad',
    subtitle: 'Perfiles de liderazgo, gestion y crecimiento',
    keywords: [
      'negocio',
      'negocios',
      'business',
      'marketing',
      'marketing digital',
      'ventas',
      'sales',
      'liderazgo',
      'management',
      'gestion',
      'finanzas',
      'finance',
      'emprendimiento',
      'startup',
      'productividad',
      'comunicacion',
      'scrum',
      'agile',
      'project management',
      'product manager',
      'negociacion',
      'oratoria',
      'excel',
      'power bi',
    ],
  },
  {
    key: 'otros',
    title: 'Otras habilidades',
    subtitle: 'Perfiles con intereses diversos',
    keywords: [],
  },
];
